version: '2'
services:
  jhipsterapp4-app:
    image: jhipsterapp4
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterapp4-postgresql:5432/jhipsterApp4
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipsterapp4-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsterapp4-postgresql
